# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# Network Settings
#
hostname: wordpress-skeleton.local
sync_folder: 'www'

#
# Virtual Machine Settings
#
memory: 2048
cpus: 2

#
# WordPress Settings
#
version: latest
lang: ja
title: 'サイトタイトル'
multisite: false
rewrite_structure: '/archives/%post_id%/'

#
# WordPress Path
#
document_root: '/var/www'
wp_home: ''     # Path to the WP_HOME like "wp"
wp_siteurl: 'wp'  # Path to the WP_SITEURL like "wp"

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins:

#
# WordPress Options
#
options:
  blogdescription: 'サイトのディスクリプション'
  date_format_custom: 'Y.m.d'
  time_format_custom: 'H:i'
  use_smilies: false
  default_pingback_flag: false
  default_ping_status: false
  default_comment_status: false

